POST http://localhost:8080/moderator/createContent-Type: application/jsonAuthorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTAzNTg2MTUsImlkIjo2LCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjkwNDA4NjgxLCJpc3MiOiJrdW51eiB0ZXN0IHBvcnRhbGkifQ.Oh9UBPb45DcwEIZ39YrVmXVaJlcEIDJNuu-W2N_9miVf-cQ-BQYCk1gH47Hy9ZnCwgSh_RgOzc3Z0_4gLu3NUA{  "title": "Example Title",  "description": "Example Description",  "content": "This is the content of the article.",  "regionId": 1,  "categoryId": 1,  "publishedDate": "2023-07-28T10:00:00"}