###POST http://localhost:8080/categoryContent-Type: application/json{  "orderNumber": 6,  "nameUZ": "UZBEKCHA",  "nameRU": "RUSSKIY",  "nameEN": "ENGLISH",  "visibility": true}<> 2023-07-21T153451.201.json###PUT http://localhost:8080/category/4Content-Type: application/json{  "orderNumber": 4,  "nameUZ": "UZ",  "nameRU": "RU",  "nameEN": "EN",  "visibility": true}<> 2023-07-21T153529.405.json<> 2023-07-21T153508.201.json###DELETE http://localhost:8080/category/2<> 2023-07-21T153544.200.txt<> 2023-07-21T153538.200.txt###GET http://localhost:8080/category/ru<> 2023-07-21T153548.200.json