###POST http://localhost:8080/profileContent-Type: application/json{  "name": "alish",  "surname": "alishov",  "email": "alish@gmail.com",  "phone": "111",  "password": "23443",  "status": "ACTIVE",  "role": "USER",  "visibility": true}###POST http://localhost:8080/profile/1Content-Type: application/json{  "name": "Qodir",  "surname": "aliyev",  "email": "ali@gmail.com",  "phone": "90282345",  "password": "12345678",  "status": "ACTIVE",  "role": "USER",  "visibility": true}###GET http://localhost:8080/profile###GET http://localhost:8080/profile<> 2023-07-14T174232.500.json###DELETE http://localhost:8080/profile/1